### ISSUE TITLE
Restore Region

### ISSUE THREAD

**Issue by zontreck** [punyauk/quintonia#1]
When restoring a region from archive, object ids get regenerated causing the farm to become corrupt in some cases, and be reset for other things like plants.

**Comment by zontreck** [comment]
To reproduce,
1. set up a farm
2. save an oar
3. Restore oar, observe above mentioned behavior


Result is ingredients are invalid, farm is reset

**Comment by zontreck** [comment]
This problem is caused by the object unique channel mismatching the new one after restore. The check is performed in on rez

**Comment by punyauk** [comment]
I have done restores before and all seems to work as expected. I know others have also. Some things will be reset as that is just how opensim OAR restores work. If things are getting corrupted that sounds more like an issue with the underlying setup of opensim you are using.
